version: '3.8'
services:
  karatedopi-backend:
    image: 'jonataslaet/karatedopi-backend'
    build:
      context: .
      dockerfile: ./backend-java/Dockerfile
    depends_on:
      - postgres-server
    ports:
      - 8080:8080
    environment:
      - APP_PROFILE=dev
      - DB_URL=jdbc:postgresql://postgres-server:5432/dbkaratedopi
      - DB_USERNAME=jonataslaet
      - DB_PASSWORD=blendo273
    networks:
      - karatedopi-network

  postgres-server:
    image: 'postgres'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=jonataslaet
      - POSTGRES_PASSWORD=blendo273
      - POSTGRES_DB=dbkaratedopi
    networks:
      - karatedopi-network

  postgres-server-test:
    image: 'postgres'
    command: -p 5433
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=jonataslaet
      - POSTGRES_PASSWORD=blendo273
      - POSTGRES_DB=dbtestkaratedopi
    networks:
      - karatedopi-network

networks:
  karatedopi-network:
    driver: bridge