version: '3.8'
services:
  postgres-server:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=jonataslaet
      - POSTGRES_PASSWORD=blendo273
      - POSTGRES_DB=dbkaratedopi
    ports:
      - '5432:5432'
    networks:
      - karatedopi-network
  karatedopi-container-dev:
    image: jonataslaet/karatedopi
    restart: always
    build: ./backend-java
    working_dir: /backend-java
    mem_limit: 500m
    ports:
      - '80:8080'
    networks:
      - karatedopi-network
    command: mvn spring-boot:run
    depends_on:
      - postgres-server
    environment:
      - SPRING.PROFILES.ACTIVE=dev
      - SPRING.DATASOURCE.URL=jdbc:postgresql://postgres-server:5432/dbkaratedopi
      - SPRING.DATASOURCE.USERNAME=jonataslaet
      - SPRING.DATASOURCE.PASSWORD=blendo273
networks:
  karatedopi-network:
    driver: bridge