version: '3.8'
services:
  postgres-server:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=jonataslaet
      - POSTGRES_PASSWORD=blendo273
      - POSTGRES_DB=dbkaratedopi
    ports:
      - '5432:5432'
    networks:
      - karatedopi-network
  karatedopi-container-dev:
    image: jonataslaet/karatedopi
    restart: always
    build: ./backend-java
    working_dir: /backend-java
    mem_limit: 500m
    ports:
      - '8080:8080'
    networks:
      - dev-network
    depends_on:
      - postgres-server
    environment:
      - APP_PROFILE=dev
      - DB_URL=jdbc:postgresql://postgres-server:5432/dbkaratedopi
      - DB_USERNAME=jonataslaet
      - DB_PASSWORD=blendo273
networks:
  karatedopi-network: