## jpa
server.port=8081
spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

## Especifica a origem dos dados (datasource)
spring.datasource.initialization-mode=always
spring.datasource.url=jdbc:mysql://localhost:3306/dbkaratedopi?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Fortaleza
spring.datasource.username=jonataslaet
spring.datasource.password=blendo273
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

## Permite que o Hibernate gere SQL otimizadas para um determinado SGBD
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect