name: Continuous Integration with Github Actions

on:
  push:
    branches: 
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      working-directory: ./backend-java
      run: mvn -B clean package

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
          context: ./backend-java
          push: true