name: Continuous Integration with Github Actions

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      working-directory: ./backend-java
      run: mvn -B clean package -DskipTests

    - name: Extract version from pom.xml
      id: extract-version
      run: echo "::set-output name=version::$(grep -oPm1 "(?<=<version>)[^<]+" ./backend-java/pom.xml)"

    - name: Build and push Docker images for Backend
      working-directory: ./backend-java
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/karatedopi-backend:latest .
        DOCKER_TAG=$(basename $(find . -name "karatedopi-*.jar") .jar | sed 's/karatedopi-//')
        docker tag ${{ secrets.DOCKER_USERNAME }}/karatedopi:latest ${{ secrets.DOCKER_USERNAME }}/karatedopi-backend:$DOCKER_TAG
        docker push ${{ secrets.DOCKER_USERNAME }}/karatedopi:$DOCKER_TAG
        docker push ${{ secrets.DOCKER_USERNAME }}/karatedopi:latest
