name: Continuous Integration with Github Actions

on:
  push:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2.0.0
        with: 
          username: {{ secrets.DOCKER_USERNAME }}
          password: {{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build Application JAR
        working-directory: ./backend-java
        run: mvn clean package

      - name: Docker Compose Build
        working-directory: ./backend-java
        run: docker compose build

      - name: Push to Docker Hub Container Registry
        working-directory: ./backend-java
        run: 
          docker tag {{ secrets.DOCKER_USERNAME }}/karatedopi:latest {{ secrets.DOCKER_USERNAME }}/karatedopi:${{ github.run_id }}
          docker push {{ secrets.DOCKER_USERNAME }}/karatedopi:{{ github.run_id }}